# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(max_length=800),
        ),
    ]
