# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170612_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
