# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170612_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvd_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
