# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
