# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_dvd_dvd_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
