# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_dvd_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='slug',
        ),
    ]
