# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_newspaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=250, unique=True)),
                ('artist', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=0, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
