# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_book_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
