# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20170615_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
