# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_remove_book_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvd',
            options={'verbose_name_plural': "DVD's"},
        ),
        migrations.AlterModelOptions(
            name='mags',
            options={'verbose_name_plural': 'Magazines'},
        ),
        migrations.AlterModelOptions(
            name='newspaper',
            options={'verbose_name_plural': 'Newspapers'},
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvd',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mags',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspaper',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
