# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20170615_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='topic',
            field=models.CharField(max_length=250),
        ),
    ]
