# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-22 04:43
from __future__ import unicode_literals

from django.db import migrations, models

def data_migration(apps, schema_editor):
    Book = apps.get_model('tracker','Book')
    Newspaper = apps.get_model('tracker','Newspaper')
    Mags = apps.get_model('tracker','Mags')
    Music = apps.get_model('tracker','Music')
    DVD = apps.get_model('tracker','DVD')
    Item = apps.get_model('tracker','Item')

    for x in Book.objects.all():
        item = Item.objects.create(name=x.name, creator=x.creator, description=x.description, slug=x.slug)
        x.item = item
        x.save()

    for x in Newspaper.objects.all():
        item = Item.objects.create(name=x.name, creator='', description='', slug=x.slug)
        x.item = item
        x.save()
    
    for x in Mags.objects.all():
        item = Item.objects.create(name=x.name, creator='', description='', slug=x.slug)
        x.item = item
        x.save()

    for x in Music.objects.all():
        item = Item.objects.create(name=x.name, creator=x.creator, description='', slug=x.slug)
        x.item = item
        x.save()
    
    for x in DVD.objects.all():
        item = Item.objects.create(name=x.name, creator='', description='', slug=x.slug)
        x.item = item
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20170622_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_cover',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='dvd_cover',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='dvd_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mags',
            old_name='mag_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='album',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='artist',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='newspaper',
            old_name='newspaper_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True),
        ),

        migrations.RunPython(data_migration),
    ]
