# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-22 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20170622_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mags',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mags',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='music',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='music',
            name='name',
        ),
        migrations.RemoveField(
            model_name='music',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='slug',
        ),
    ]
