# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20170622_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='topic',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
