# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_remove_item_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='creator',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='topic',
        ),
    ]
