# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='dvd_cover',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='isbn',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='topic',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
