# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_auto_20170623_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='topic',
        ),
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='isbn',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='topic',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
