# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_auto_20170623_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='item',
            name='topic',
        ),
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mags',
            name='mag_cover',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='album_cover',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspaper',
            name='newspaper_cover',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
