# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20170623_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_cover',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='mags',
            name='mag_cover',
        ),
        migrations.RemoveField(
            model_name='music',
            name='album_cover',
        ),
        migrations.RemoveField(
            model_name='newspaper',
            name='newspaper_cover',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
