# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_auto_20170623_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
