# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_auto_20170623_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='newspaper_cover',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
