# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_auto_20170623_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='item',
            name='topic',
        ),
    ]
