# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_auto_20170623_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookstuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=250, unique=True)),
                ('topic', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
