# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_bookstuff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookstuff',
        ),
        migrations.AddField(
            model_name='item',
            name='isbn',
            field=models.CharField(default=0, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='topic',
            field=models.CharField(default=0, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
