# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_auto_20170623_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='item',
            name='topic',
        ),
        migrations.AddField(
            model_name='book',
            name='checkouts',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
