# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_auto_20170623_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkouts',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.CharField(max_length=250),
        ),
    ]
