# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_auto_20170623_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checkouts',
        ),
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
    ]
